services:
  copick-server:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - BUILDKIT_INLINE_CACHE=1
    platform: linux/amd64 # copick depends on numcodecs 0.15.1 which is not available for arm64
    volumes:
      - .:/app
    ports:
      - "8091:8091"
    command: ["uv", "run", "copick_server/server.py", "example_copick.json", "--host", "0.0.0.0", "--port", "8091"]
networks:
  default:
    name: copick-server
    driver: overlay
    attachable: true