stack:
  services:
    copick-server:
      image:
        tag: sha-000000
      replicaCount: 1
      env:
        - name: DATABASE_HOST
          value: $(__ARGUS_STACK_NAME)-postgresql
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_NAME
          value: copick-server
      