stack:
  global:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: copick-auth
        nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header Authorization $http_authorization;
  services:
    copick-server:
      image:
        tag: sha-4dced1f
      replicaCount: 1
      env:
        - name: PORT
          value: "8012"
        - name: HOST
          value: "0.0.0.0"
        - name: OVERLAY_ROOT
          value: /mnt/copick/overlay
