name: Docker Build Rdev

on:
  push:
  pull_request:
      types: [ labeled ]

jobs:
  rdev_argus_builder:
    uses: ./.github/workflows/workflow-argus-docker-build.yaml
    secrets: inherit
    with:
      envs: rdev
      path_filters: '!.infra/**'
      branches_ignore: main,release-please--branches--main